### PR TITLE
Allow to set an custom SSLContext to ConnectionManager

### PR DESCRIPTION
**Pull request by leandrohsilveira**
Related to issue #143.

### CODE REVIEW

**Comment by leandrohsilveira** [comment]
Yes, we tested in our environment and works properly.
About overwriting the SSLContext when used the certificate credential to authenticate, I believe that's what should happen. I just wonder if this will be confusing to those who use the CertificateCredential authentication method.

I can add to javadoc the method "configureCustomSslContext" an explanation that this property can be overridden if authentication is by certificate.

Or I should think of another way to configure the SSLContext for other types of credentials?

**Comment by juwlee** [comment]
Yes, adding the warning message to javadoc sounds reasonable. If you could add a couple of your java code to show the usage, that would be great.

**Comment by leandrohsilveira** [comment]
I've added the javadoc.
About adding some java code, where i can post it?

**Comment by juwlee** [comment]
I think the in the javadoc itself would be fine. You might want to [wrap it in javadoc tags as shown here](http://stackoverflow.com/questions/541920/multiple-line-code-example-in-javadoc-comment) to have it correctly formatted.

**Comment by leandrohsilveira** [comment]
I added a bit of our code. With some adjustments to remove the JEE technology code to not be out of context.
In the example I changed the part that loads the SSLContext. In java doc it is "" But in our case the certificate is loaded from a server directory.

It is enough?

:)

**Comment by juwlee** [comment]
Yes, thanks again @leandrohsilveira !

**Pull request merged**
